### ISSUE TITLE
`LocalDateTimes` does not accept midnight time

### ISSUE THREAD

**Issue by yuri-sergiichuk** [SpineEventEngine/time#37]
It's currently not possible to create a `LocalTime` instance that denotes the midnight time — `00:00:00` using `LocalDateTimes`.

There is a special `checkTime` check that required a valid `LocalTime` Protobuf entity to be supplied. And in fact, a `00:00:00` time should be valid, but `checkNotDefault` method treats a Protobuf entity with all `0` values as `default`.

The expected behavior is to allow the creation of a `LocalDateTime` instance where time is equal to `00:00:00`.

**Comment by alexander-yevsyukov** [comment]
Fixed in #38.
